# Generated by Django 5.1.2 on 2024-10-12 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuranceApp', '0002_rename_insuranceproposal_insuranceappproposal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(max_length=100)),
                ('claim_description', models.TextField()),
                ('claim_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='insuranceappproposal',
            name='vehicle_make',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='insuranceappproposal',
            name='vehicle_model',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='insuranceappproposal',
            name='vehicle_year',
            field=models.PositiveIntegerField(),
        ),
    ]
