# Generated by Django 5.1.2 on 2024-10-12 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuranceApp', '0003_claim_alter_insuranceappproposal_vehicle_make_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
